"""Generate the reproducibility appendix for sampled project versions."""

from __future__ import annotations

import argparse
from pathlib import Path
from urllib.parse import quote

import pandas as pd

from helpers import SOURCERY_DB, load_data, version_commit_hash

SAMPLE_COUNT = 10
PROJECT_COUNT = 20
DEFAULT_OUTPUT = Path(__file__).resolve().parent / "sampled_projects_versions.typ"


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Generate a Typst table of sampled projects and commits."
    )
    parser.add_argument(
        "--data-dir",
        type=Path,
        default=Path(__file__).resolve().parent,
        help="Directory containing the numbered metrics CSV files.",
    )
    parser.add_argument(
        "--output",
        type=Path,
        default=DEFAULT_OUTPUT,
        help=f"Typst output file (default: {DEFAULT_OUTPUT}).",
    )
    parser.add_argument(
        "--sourcery-db",
        type=Path,
        default=SOURCERY_DB,
        help=f"sourcery-db executable (default: {SOURCERY_DB}).",
    )
    return parser.parse_args()


def sampled_projects(data_dir: Path, sourcery_db: Path) -> pd.DataFrame:
    """Return one row per project and sample, including the exact commit hash."""
    metrics = load_data(data_dir).raw_metrics
    project_columns = ["codebase_id", "codebase_name", "programming_language"]
    projects = (
        metrics[project_columns]
        .drop_duplicates()
        .sort_values(["programming_language", "codebase_name"])
        .reset_index(drop=True)
    )
    if len(projects) != PROJECT_COUNT:
        raise ValueError(f"expected {PROJECT_COUNT} projects, found {len(projects)}")

    rows = []
    for project in projects.itertuples(index=False):
        repository = project.codebase_name.split(" (", 1)[0]
        if "__" not in repository:
            raise ValueError(f"cannot derive GitHub repository from {repository!r}")
        owner, name = repository.split("__", 1)
        for sample_number in range(1, SAMPLE_COUNT + 1):
            commit_hash = version_commit_hash(
                project.codebase_id, sample_number, sourcery_db
            )
            if commit_hash is None:
                raise ValueError(
                    f"no sample {sample_number} commit found for {repository}"
                )
            rows.append(
                {
                    "repository": repository,
                    "owner": owner,
                    "name": name,
                    "programming_language": project.programming_language,
                    "sample_number": sample_number,
                    "commit_hash": commit_hash,
                }
            )
    return pd.DataFrame(rows)


def typst_string(value: str) -> str:
    """Escape a value for use in a Typst string literal."""
    return value.replace("\\", "\\\\").replace('"', '\\"')


def format_typst(rows: pd.DataFrame) -> str:
    """Format sampled projects as an includable Typst appendix section."""
    output = [
        "// Generated by generate_sampled_projects_typ.py; do not edit manually.",
        "= Sampled projects and versions <sampled-project-versions>",
        "",
        (
            "The analysis sampled ten versions of each of the 20 projects listed "
            "below. Full commit hashes are provided to make the analyzed source "
            "versions reproducible. Each hash links to the corresponding GitHub "
            "commit."
        ),
        "",
        "#table(",
        "  columns: (1.2fr, 17mm, 2.4fr),",
        "  inset: 4pt,",
        "  align: (left, left, left),",
        "  table.header([*Project*], [*Language*], [*Sampled versions*]),",
    ]

    for (_, language), project_rows in rows.groupby(
        ["repository", "programming_language"], sort=False
    ):
        first = project_rows.iloc[0]
        repository = str(first["repository"])
        owner = quote(str(first["owner"]), safe="")
        name = quote(str(first["name"]), safe="")
        repo_url = f"https://github.com/{owner}/{name}"
        output.extend(
            [
                f'  [#link("{repo_url}")[#raw("{typst_string(repository)}")]],',
                f"  [{language}],",
                "  [#table(",
                "    columns: (8mm, 1fr),",
                "    inset: (x: 0pt, y: 1pt),",
                "    stroke: none,",
            ]
        )
        for row in project_rows.itertuples(index=False):
            commit_hash = str(row.commit_hash)
            commit_url = f"{repo_url}/commit/{quote(commit_hash, safe='')}"
            output.append(
                f"    [v{row.sample_number}], "
                f'[#link("{commit_url}")[#raw("{typst_string(commit_hash)}")]],'
            )
        output.extend(["  )],"])

    output.extend([")", ""])
    return "\n".join(output)


def main() -> None:
    args = parse_args()
    rows = sampled_projects(args.data_dir, args.sourcery_db)
    args.output.write_text(format_typst(rows))
    print(f"Wrote {len(rows)} sampled versions to {args.output}")


if __name__ == "__main__":
    main()
