#set page(width: 297mm, height: 210mm, margin: 10mm)
#set text(size: 7pt)

= Go vs OCaml metric values by version

A listed version means that language has the strictly lower value. Callgraph values come from `callgraph_results/callgraph_linechart_*.csv`; all other values come from `metrics_over_versions_*.csv`.

== Summary

#table(
  columns: (18mm, 1fr, 1fr, 1fr),
  inset: 4pt,
  align: (left, center, center, center),
  table.header(
    [*Level*], [*OCaml lower*], [*Go lower*], [*Equal*],
  ),
  [Overall], [1,001 / 1,700 (58.9%)], [668 / 1,700 (39.3%)], [31 / 1,700 (1.8%)],
  [File], [474 / 700 (67.7%)], [225 / 700 (32.1%)], [1 / 700 (0.1%)],
  [Function], [366 / 460 (79.6%)], [80 / 460 (17.4%)], [14 / 460 (3.0%)],
  [Version], [161 / 540 (29.8%)], [363 / 540 (67.2%)], [16 / 540 (3.0%)],
)

Excluding ties, OCaml is lower in 1,001 / 1,669 comparisons (60.0%).

== Detailed comparisons

#table(
  columns: (13mm, 1fr, 14mm, 34mm, 34mm, 28mm),
  inset: 3pt,
  align: (left, left, center, left, left, left),
  table.header(
    [*Level*], [*Metric*], [*Statistic*], [*OCaml lower*],
    [*Go lower*], [*Equal*],
  ),
  [File], [bracket lines of code], [Mean], [v1-v10], [none], [none],
  [File], [bracket lines of code], [Median], [v1-v10], [none], [none],
  [File], [comment lines of code], [Mean], [v2], [v1, v3-v10], [none],
  [File], [comment lines of code], [Median], [v2-v10], [v1], [none],
  [File], [cyclomatic per line], [Mean], [v1-v10], [none], [none],
  [File], [cyclomatic per line], [Median], [v1-v10], [none], [none],
  [File], [cyclomatic per line (Ocaml .ml only)], [Mean], [v2, v10], [v1, v3-v9], [none],
  [File], [cyclomatic per line (Ocaml .ml only)], [Median], [v2-v10], [v1], [none],
  [File], [effective lines of code], [Mean], [v2, v7-v10], [v1, v3-v6], [none],
  [File], [effective lines of code], [Median], [v1-v10], [none], [none],
  [File], [effective lines of code with brackets], [Mean], [v2, v6-v10], [v1, v3-v5], [none],
  [File], [effective lines of code with brackets], [Median], [v1-v10], [none], [none],
  [File], [lines of code], [Mean], [v2, v7-v10], [v1, v3-v6], [none],
  [File], [lines of code], [Median], [v1-v10], [none], [none],
  [File], [maintainability index comment percentage], [Mean], [v2], [v1, v3-v10], [none],
  [File], [maintainability index comment percentage], [Median], [v2-v10], [v1], [none],
  [File], [maintainability index four property], [Mean], [v1], [v2-v10], [none],
  [File], [maintainability index four property], [Median], [v1], [v2-v10], [none],
  [File], [maintainability index three property], [Mean], [none], [v1-v10], [none],
  [File], [maintainability index three property], [Median], [none], [v1-v10], [none],
  [File], [maintainability index visual studio], [Mean], [none], [v1-v10], [none],
  [File], [maintainability index visual studio], [Median], [none], [v1-v10], [none],
  [File], [mean cyclomatic per function per file], [Mean], [v1-v10], [none], [none],
  [File], [mean cyclomatic per function per file], [Median], [v1-v10], [none], [none],
  [File], [mean cyclomatic per function per file (Ocaml .ml only)], [Mean], [v1-v10], [none], [none],
  [File], [mean cyclomatic per function per file (Ocaml .ml only)], [Median], [v1-v10], [none], [none],
  [File], [mean indegree per file], [Mean], [v1-v10], [none], [none],
  [File], [mean indegree per file], [Median], [v1-v10], [none], [none],
  [File], [mean outdegree per file], [Mean], [v1-v10], [none], [none],
  [File], [mean outdegree per file], [Median], [v1-v10], [none], [none],
  [File], [mean unique indegree per file], [Mean], [v1-v10], [none], [none],
  [File], [mean unique indegree per file], [Median], [v1-v10], [none], [none],
  [File], [mean unique outdegree per file], [Mean], [v1-v10], [none], [none],
  [File], [mean unique outdegree per file], [Median], [v1, v3-v10], [v2], [none],
  [File], [total cyclomatic], [Mean], [v2, v6-v10], [v1, v3-v5], [none],
  [File], [total cyclomatic], [Median], [v1-v10], [none], [none],
  [File], [total cyclomatic (Ocaml .ml only)], [Mean], [v2], [v1, v3-v10], [none],
  [File], [total cyclomatic (Ocaml .ml only)], [Median], [v2-v3, v5-v10], [v1], [v4],
  [File], [total halstead bugs], [Mean], [v2-v3, v9-v10], [v1, v4-v8], [none],
  [File], [total halstead bugs], [Median], [v1-v10], [none], [none],
  [File], [total halstead calculated length], [Mean], [v1-v3, v6-v10], [v4-v5], [none],
  [File], [total halstead calculated length], [Median], [v1-v10], [none], [none],
  [File], [total halstead difficulty], [Mean], [v2, v8-v10], [v1, v3-v7], [none],
  [File], [total halstead difficulty], [Median], [v1-v10], [none], [none],
  [File], [total halstead effort], [Mean], [v2], [v1, v3-v10], [none],
  [File], [total halstead effort], [Median], [v1-v10], [none], [none],
  [File], [total halstead length], [Mean], [v2, v9-v10], [v1, v3-v8], [none],
  [File], [total halstead length], [Median], [v1-v10], [none], [none],
  [File], [total halstead operands], [Mean], [v2-v3, v7-v10], [v1, v4-v6], [none],
  [File], [total halstead operands], [Median], [v1-v10], [none], [none],
  [File], [total halstead operators], [Mean], [v2], [v1, v3-v10], [none],
  [File], [total halstead operators], [Median], [v2, v9-v10], [v1, v3-v8], [none],
  [File], [total halstead time seconds], [Mean], [v2], [v1, v3-v10], [none],
  [File], [total halstead time seconds], [Median], [v1-v10], [none], [none],
  [File], [total halstead unique operands], [Mean], [v1-v3, v6-v10], [v4-v5], [none],
  [File], [total halstead unique operands], [Median], [v1-v10], [none], [none],
  [File], [total halstead unique operators], [Mean], [v1-v10], [none], [none],
  [File], [total halstead unique operators], [Median], [v1-v10], [none], [none],
  [File], [total halstead vocabulary], [Mean], [v1-v3, v6-v10], [v4-v5], [none],
  [File], [total halstead vocabulary], [Median], [v1-v10], [none], [none],
  [File], [total halstead volume], [Mean], [v2-v3, v9-v10], [v1, v4-v8], [none],
  [File], [total halstead volume], [Median], [v1-v10], [none], [none],
  [File], [total indegree per file], [Mean], [v1-v10], [none], [none],
  [File], [total indegree per file], [Median], [v1-v10], [none], [none],
  [File], [total outdegree per file], [Mean], [none], [v1-v10], [none],
  [File], [total outdegree per file], [Median], [none], [v1-v10], [none],
  [File], [total unique indegree per file], [Mean], [v1-v10], [none], [none],
  [File], [total unique indegree per file], [Median], [v1-v10], [none], [none],
  [File], [total unique outdegree per file], [Mean], [none], [v1-v10], [none],
  [File], [total unique outdegree per file], [Median], [none], [v1-v10], [none],
  [Function], [cyclomatic], [Mean], [v1-v10], [none], [none],
  [Function], [cyclomatic], [Median], [v1-v10], [none], [none],
  [Function], [cyclomatic match as single branch], [Mean], [v1-v10], [none], [none],
  [Function], [cyclomatic match as single branch], [Median], [v1-v10], [none], [none],
  [Function], [function length], [Mean], [v1, v3-v10], [v2], [none],
  [Function], [function length], [Median], [v1-v10], [none], [none],
  [Function], [halstead bugs], [Mean], [v1, v3-v10], [v2], [none],
  [Function], [halstead bugs], [Median], [v1-v10], [none], [none],
  [Function], [halstead calculated length], [Mean], [v1, v3-v10], [v2], [none],
  [Function], [halstead calculated length], [Median], [v1-v10], [none], [none],
  [Function], [halstead difficulty], [Mean], [v1-v10], [none], [none],
  [Function], [halstead difficulty], [Median], [v1-v10], [none], [none],
  [Function], [halstead effort], [Mean], [v1, v7-v10], [v2-v6], [none],
  [Function], [halstead effort], [Median], [v1-v10], [none], [none],
  [Function], [halstead length], [Mean], [v1, v3-v10], [v2], [none],
  [Function], [halstead length], [Median], [v1-v10], [none], [none],
  [Function], [halstead operands], [Mean], [v1, v3-v10], [v2], [none],
  [Function], [halstead operands], [Median], [v1-v10], [none], [none],
  [Function], [halstead operators], [Mean], [v1, v3, v5-v10], [v2, v4], [none],
  [Function], [halstead operators], [Median], [v1-v10], [none], [none],
  [Function], [halstead time seconds], [Mean], [v1, v7-v10], [v2-v6], [none],
  [Function], [halstead time seconds], [Median], [v1-v10], [none], [none],
  [Function], [halstead unique operands], [Mean], [v1, v3-v10], [v2], [none],
  [Function], [halstead unique operands], [Median], [v1-v10], [none], [none],
  [Function], [halstead unique operators], [Mean], [v1-v10], [none], [none],
  [Function], [halstead unique operators], [Median], [v1-v10], [none], [none],
  [Function], [halstead vocabulary], [Mean], [v1, v3-v10], [v2], [none],
  [Function], [halstead vocabulary], [Median], [v1-v10], [none], [none],
  [Function], [halstead volume], [Mean], [v1, v3-v10], [v2], [none],
  [Function], [halstead volume], [Median], [v1-v10], [none], [none],
  [Function], [indegree], [Mean], [v1-v10], [none], [none],
  [Function], [indegree], [Median], [v1, v3-v10], [none], [v2],
  [Function], [maintainability index comment percentage], [Mean], [v1-v10], [none], [none],
  [Function], [maintainability index comment percentage], [Median], [none], [none], [v1-v10],
  [Function], [maintainability index four property], [Mean], [none], [v1-v10], [none],
  [Function], [maintainability index four property], [Median], [none], [v1-v10], [none],
  [Function], [maintainability index three property], [Mean], [none], [v1-v10], [none],
  [Function], [maintainability index three property], [Median], [none], [v1-v10], [none],
  [Function], [maintainability index visual studio], [Mean], [none], [v1-v10], [none],
  [Function], [maintainability index visual studio], [Median], [none], [v1-v10], [none],
  [Function], [outdegree], [Mean], [v1-v10], [none], [none],
  [Function], [outdegree], [Median], [v1-v3, v6-v10], [none], [v4-v5],
  [Function], [unique indegree], [Mean], [v1-v10], [none], [none],
  [Function], [unique indegree], [Median], [v1, v3-v10], [none], [v2],
  [Function], [unique outdegree], [Mean], [v1-v10], [none], [none],
  [Function], [unique outdegree], [Median], [v1-v10], [none], [none],
  [Version], [files], [Mean], [v2], [v1, v3-v10], [none],
  [Version], [files], [Median], [none], [v1-v10], [none],
  [Version], [files with maintainability index], [Mean], [v2], [v1, v3-v10], [none],
  [Version], [files with maintainability index], [Median], [none], [v1-v10], [none],
  [Version], [total bracket lines of code], [Mean], [v2-v10], [v1], [none],
  [Version], [total bracket lines of code], [Median], [v1-v10], [none], [none],
  [Version], [total comment lines of code], [Mean], [v2], [v1, v3-v10], [none],
  [Version], [total comment lines of code], [Median], [none], [v1-v10], [none],
  [Version], [total cyclomatic], [Mean], [v2, v9-v10], [v1, v3-v8], [none],
  [Version], [total cyclomatic], [Median], [v8-v10], [v1-v7], [none],
  [Version], [total effective lines of code], [Mean], [v2, v10], [v1, v3-v9], [none],
  [Version], [total effective lines of code], [Median], [v10], [v1-v9], [none],
  [Version], [total effective lines of code with brackets], [Mean], [v2, v9-v10], [v1, v3-v8], [none],
  [Version], [total effective lines of code with brackets], [Median], [v9-v10], [v1-v8], [none],
  [Version], [total four property maintainability index], [Mean], [v1, v3-v8], [v2, v9-v10], [none],
  [Version], [total four property maintainability index], [Median], [v1-v8], [v9-v10], [none],
  [Version], [total halstead bugs], [Mean], [v2, v10], [v1, v3-v9], [none],
  [Version], [total halstead bugs], [Median], [v10], [v1-v9], [none],
  [Version], [total halstead calculated length], [Mean], [v2, v9-v10], [v1, v3-v8], [none],
  [Version], [total halstead calculated length], [Median], [v10], [v1-v9], [none],
  [Version], [total halstead difficulty], [Mean], [v2, v10], [v1, v3-v9], [none],
  [Version], [total halstead difficulty], [Median], [v10], [v1-v9], [none],
  [Version], [total halstead effort], [Mean], [v2, v10], [v1, v3-v9], [none],
  [Version], [total halstead effort], [Median], [v10], [v1-v9], [none],
  [Version], [total halstead length], [Mean], [v2, v10], [v1, v3-v9], [none],
  [Version], [total halstead length], [Median], [v10], [v1-v9], [none],
  [Version], [total halstead operands], [Mean], [v2, v10], [v1, v3-v9], [none],
  [Version], [total halstead operands], [Median], [v9-v10], [v1-v8], [none],
  [Version], [total halstead operators], [Mean], [v2], [v1, v3-v10], [none],
  [Version], [total halstead operators], [Median], [none], [v1-v10], [none],
  [Version], [total halstead time seconds], [Mean], [v2, v10], [v1, v3-v9], [none],
  [Version], [total halstead time seconds], [Median], [v10], [v1-v9], [none],
  [Version], [total halstead unique operands], [Mean], [v2, v9-v10], [v1, v3-v8], [none],
  [Version], [total halstead unique operands], [Median], [v10], [v1-v9], [none],
  [Version], [total halstead unique operators], [Mean], [v2, v10], [v1, v3-v9], [none],
  [Version], [total halstead unique operators], [Median], [v2], [v1, v3-v10], [none],
  [Version], [total halstead vocabulary], [Mean], [v2, v9-v10], [v1, v3-v8], [none],
  [Version], [total halstead vocabulary], [Median], [v10], [v1-v9], [none],
  [Version], [total halstead volume], [Mean], [v2, v10], [v1, v3-v9], [none],
  [Version], [total halstead volume], [Median], [v10], [v1-v9], [none],
  [Version], [total indegree per version], [Mean], [v2-v10], [v1], [none],
  [Version], [total indegree per version], [Median], [v1-v10], [none], [none],
  [Version], [total lines of code], [Mean], [v2, v10], [v1, v3-v9], [none],
  [Version], [total lines of code], [Median], [v10], [v1-v9], [none],
  [Version], [total outdegree per version], [Mean], [v2, v9-v10], [v1, v3-v8], [none],
  [Version], [total outdegree per version], [Median], [v6-v10], [v1-v5], [none],
  [Version], [total three property maintainability index], [Mean], [v1, v3-v8], [v2, v9-v10], [none],
  [Version], [total three property maintainability index], [Median], [v1-v7], [v8-v10], [none],
  [Version], [total unique indegree per version], [Mean], [v2-v10], [v1], [none],
  [Version], [total unique indegree per version], [Median], [v1-v10], [none], [none],
  [Version], [total unique outdegree per version], [Mean], [v2, v10], [v1, v3-v9], [none],
  [Version], [total unique outdegree per version], [Median], [v6-v10], [v1-v5], [none],
  [Version], [total visual studio maintainability index], [Mean], [v1], [v2-v3], [v4-v10],
  [Version], [total visual studio maintainability index], [Median], [v1], [none], [v2-v10],
)
