/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DiffGraphRouteImport } from './routes/diff-graph'
import { Route as CodebaseRouteImport } from './routes/codebase'
import { Route as IndexRouteImport } from './routes/index'

const DiffGraphRoute = DiffGraphRouteImport.update({
  id: '/diff-graph',
  path: '/diff-graph',
  getParentRoute: () => rootRouteImport,
} as any)
const CodebaseRoute = CodebaseRouteImport.update({
  id: '/codebase',
  path: '/codebase',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/codebase': typeof CodebaseRoute
  '/diff-graph': typeof DiffGraphRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/codebase': typeof CodebaseRoute
  '/diff-graph': typeof DiffGraphRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/codebase': typeof CodebaseRoute
  '/diff-graph': typeof DiffGraphRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/codebase' | '/diff-graph'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/codebase' | '/diff-graph'
  id: '__root__' | '/' | '/codebase' | '/diff-graph'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CodebaseRoute: typeof CodebaseRoute
  DiffGraphRoute: typeof DiffGraphRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/diff-graph': {
      id: '/diff-graph'
      path: '/diff-graph'
      fullPath: '/diff-graph'
      preLoaderRoute: typeof DiffGraphRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/codebase': {
      id: '/codebase'
      path: '/codebase'
      fullPath: '/codebase'
      preLoaderRoute: typeof CodebaseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CodebaseRoute: CodebaseRoute,
  DiffGraphRoute: DiffGraphRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
